version: 1.0.{build}
before_build:
  - nuget restore
build:
  verbosity: minimal
after_build:
- cmd: packages\Tools.InnoSetup.5.5.8\tools\ISCC Installer\TInstallerScript.iss
artifacts:
- path: Installer\Setup\*.exe
  type: WebDeployPackage
  name: InstallerPackage
init:
  - echo appveyor_repo_tag is %APPVEYOR_REPO_TAG%
deploy:
  release: TanksStory-v$(appveyor_build_version)
  description: Another release
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: $(GH_TOKEN)  # Use the environment variable
 
  artifact: InstallerPackage
  draft: false
  prerelease: false
  on:
    #branch: master
    appveyor_repo_tag: true

environment:
  GH_TOKEN: $GH_TOKEN  # This will use the token stored in your AppVeyor settings

build_script:
  - git config --global url."https://$GH_TOKEN@github.com/".insteadOf "https://github.com/"
  - git fetch origin
    



